### PR TITLE
Add count to release button

### PR DESCRIPTION
**Pull request by ltwp**
modified counter_button class—re issue #20

### CODE REVIEW

**Comment by jackjennings** [comment]
Looks great! @ltwp's first commit to `ghostlines-robofont` 🎉

**Review by jackjennings — APPROVED** [review]
Looks great! @ltwp's first commit to `ghostlines-robofont` 🎉

**Comment by ghost** [comment]
party time! 🎊 🍕 nice work @ltwp

**Comment by ltwp** [comment]
i'd like to thank the academy 😭
and jack 😭 for all his help 😭

**Comment by jackjennings** [comment]
Don't forget to hit the big green button! 👇

**Pull request merged**
