### PR TITLE
Release version 0.3.1

### PR DESCRIPTION
**Pull request by jackjennings**
This adds the ability to send a release to a subset of the subscribers listed in the Release window.

### CODE REVIEW

**Comment by jackjennings** [comment]
screen shot 2016-11-17 at 8 53 57 pm

**Comment by jackjennings** [comment]
@ltwp can you take a look and make sure this interface makes sense? — The button label is updated when a subset is selected in the list.

**Comment by ltwp** [comment]
The button text is certainly good—but unless they select any at all, there's no indication the user can select a subset at all. 

I wonder if the "Subscribers" label could say "Subscribers (click to select)" or if next to the [ + ] [ - ] buttons there can be a line—"cmd+click to select subset".

**Comment by ltwp** [comment]
Also, if no names are selected specifically, perhaps the button text should read "Send Release to All" and then we do away with the parenthesis.

**Pull request merged**
