### PR TITLE
Refined account windows. 

### PR DESCRIPTION
**Pull request by ltwp**
Refined spacing, shrunk field labels, put sign-out button at bottom, swapped button positions.

Some screenshots:

screen shot 2017-02-03 at 15 54 27

screen shot 2017-02-03 at 15 54 19

### CODE REVIEW

**Comment by jackjennings** [comment]
A few things:

* Sign Out button right aligned, with much smaller width.
* Sign In button aligned to the right margin of window (15px to border)
* "Sign in with…" text using small text size.
* 15px space between "Sign in with…" text and email field
* 15px space between password fields and buttons.
* 15px space between buttons and bottom of window
* Resize account details window to fit the amount of existing content

The 15px spaces should be optically the same, so they might have to be prodded up or down to look correct.

**Comment by ltwp** [comment]
screen shot 2017-02-03 at 16 39 59

screen shot 2017-02-03 at 16 39 28

I'm inclined to put a bit of space between the password field and the buttons in the sign-in window, but it doesn't make much of a difference.

**Comment by ltwp** [comment]
actually the spacing between "Sign in with..." and "Email:" is now looking more than 15px. Adjusting...

**Comment by jackjennings** [comment]
I agree with you impulse to make the space between more than 15px, though my gut is to make things consistent because if we ever do automate some kind of layout manager it will be easier to drop in if the values are the same.

**Comment by jackjennings** [comment]
Account details is a little bit weird, though I think we should do some research and get a few examples of how similar information is handled in other place. I guess in the end `Account Details` will be a form where you can update the email address and password, so that will make this into a more traditional form.

**Comment by ltwp** [comment]
I think it will look much more normal once populated... with a list of fonts published via ghostlines, and a reset password button, and so forth.

**Comment by ltwp** [comment]
screen shot 2017-02-03 at 16 45 36

better.

**Comment by jackjennings** [comment]
Right—agreed. This looks good to merge as-is, though.

**Pull request merged**
